/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snap_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6b90def25a181698a264fb6be22bd73b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ata/snap_source.h>
// pydoc.h is automatically generated in the build directory
#include <snap_source_pydoc.h>

void bind_snap_source(py::module& m)
{

    using snap_source    = ::gr::ata::snap_source;


    py::class_<snap_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<snap_source>>(m, "snap_source", D(snap_source))

        .def(py::init(&snap_source::make),
           py::arg("port"),
           py::arg("headerType"),
           py::arg("notifyMissed"),
           py::arg("sourceZeros"),
           py::arg("ipv6"),
           py::arg("starting_channel"),
           py::arg("ending_channel"),
           py::arg("data_source"),
           py::arg("file") = "",
           py::arg("repeat_file") = false,
           py::arg("packed_output") = false,
           py::arg("mcast_group") = "",
           py::arg("send_start_msg") = false,
           D(snap_source,make)
        )
        



        ;




}








