/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(SNAPSynchronizerV3.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7c441cfa98c29017384b3955091ddca9)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <ata/SNAPSynchronizerV3.h>
// pydoc.h is automatically generated in the build directory
#include <SNAPSynchronizerV3_pydoc.h>

void bind_SNAPSynchronizerV3(py::module& m)
{

    using SNAPSynchronizerV3    = ::gr::ata::SNAPSynchronizerV3;


    py::class_<SNAPSynchronizerV3, gr::block, gr::basic_block,
        std::shared_ptr<SNAPSynchronizerV3>>(m, "SNAPSynchronizerV3", D(SNAPSynchronizerV3))

        .def(py::init(&SNAPSynchronizerV3::make),
           py::arg("num_inputs"),
           py::arg("num_channels"),
           D(SNAPSynchronizerV3,make)
        )
        



        ;




}








